# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
# Orchestrate or schedule a set of jobs
commands:
  print_pipeline_id:
    parameters:
      id:
        type: string
    steps:
      - run: echo << parameter.id >>
jobs:
  my_job:
    docker:
      - image: circleci/node13.8.0
    steps:
      - print_pipeline_id:
        id: << pipeline.id >>
workflows:
  my_workflow:
    jobs:
      - my_job
